/* eslint-disable  func-names */
/* eslint quote-props: ["error", "consistent"]*/

/* THIS IS A WORK IN PROGRESS */

module.exports = {
    RECIPE_EN_GB: {
        /* ---- Chemistry Station ---- */
        /* Drugs */
        'berry mentats': 'berry mentats are made with 1 anti-freeze bottle, 1 mentats and 2 tarberry.',
        'buffjet': 'you will need 1 buffout and 1 jet to make buffjet',
        'buffats': 'buffats require 1 buffout and 1 mentats to make',
        'fury': 'for fury you will need 1 berserk syringe and 1 buffout',
        'grape mentats': 'grape mentats are made with 2 hubflowers, 1 mentats and 1 whiskey',
        'jet': '2 fertilizer, 1 plastic',
        'jet fuel': '5 flamer fuel, 1 jet',
        'mentats': '1 abraxo cleaner, 2 brain fungus, 1 lead',
        'orange mentats': '1 asbestos, 3 carrots, 1 mentats',
        'overdrive': '2 acid, 1 nuka-cola, 1 psycho',
        'psycho': '1 acid, 1 circuitry, 2 hubflower, 1 stimpak',
        'psycho jet': '1 jet, 1 psycho',
        'psychobuff': '1 buffout, 1 psycho',
        'ultrajet': '1 bloodleaf, 1 fertilizer, 1 jet and 2 plastic',
        /* Grenades */
        'baseball grenade': '2 adhesive, 1 baseball, 2 fertilizer, 1 oil and 2 steel',
        'cryogenic grenade': '3 acid, 3 adhesive, 3 auminium, 2 nuclear material and 1 spring.',
        'fragmentation grenade': '3 adhesive, 2 aluminium, 2 fertilizer, 3 oil and 1 spring',
        'hallucinogen gas grenade': '3 adhesive, 2 aluminium, 1 hallucinogen gas canister and 1 ',
        'Molotov cocktail': '2 adhesive, 1 cloth, 2 glass, 4 oil',
        'Plasma grenade': '4 adhesive, 4 aluminium, 2 circuitry, 3 nuclear material, 1 spring',
        'Pulse grenade': '4 adhesive, 3 aluminium, 1 circuitry, 2 nuclear material, 1 spring',
        /* Healing */
        'glowing blood pack': '1 antiseptic, 1 blood pack, 1 irradiated blood',
        'radaway': '2 antiseptic, 3 glowing fungus, 1 plastic, 1 purified water',
        'refreshing beverage': '3 antiseptic, 1 blood pack, 2 purified water, 2 radaway, 1 stimpak',
        'robot repair kit': '2 circuitry, 4 fusion cell, 2 spring, 1 steel',
        'skeeto spit': '1 blood sac, 1 bloodleaf, 1 glass, 1 steel',
        'stimpak': '2 antiseptic, 1 blood pack, 1 steel',
        /* Mines */
        'bottlecap mine': '2 adhesive, 2 fertilizer, 2 oil, 2 steel, 1 vault-tec lunchbox',
        'cryo mine': '3 acid, 3 adhesive, 4 aluminium, 2 circuitry, 2 nuclear material',
        'fragmentation mine': '3 adhesive, 3 aluminium, 3 fertilizer, 3 oil, 2 steel',
        'plasma mine': '4 adhesive, 5 aluminium, 3 circuitry, 3 fiber optics, 3 nuclear material',
        'pulse mine': '4 adhesive, 4 aluminium, 3 circuitry, 2 fiber optics, 3 nuclear material',
        /* Utility */
        'cutting fluid': '2 acid, 8 bone, 2 purified water and 3 steel',
        'modified bowling ball': '1 acid, 1 bowling ball, 1 oil',
        /* Syringer ammo */
        'berserk syringe': '1 anti freeze bottle, 1 bourbon, 1 dirty water and 1 steel',
        'bleed out syringe': '1 fiberglass, 1 oil and 1 steel',
        'bloatfly larva': '1 bloatfly gland, 1 glass and 1 psycho',
        'endangerol syringe': '1 acid, 1 glass, 1 med-x and 1 pencil',
        'lock joint syringe': '1 dirty water, 4 lead, 1 steel, 1 stingwing barb and 2 tarberry',
        'mind cloud syringe': '1 abraxo cleaner, 2 asbestos, 1 glass and 1 purified water',
        'pax syringe': '2 mutfruit, 1 nuka-cola and 1 steel',
        'radscorpion venom syringe': '1 glass, 1 radscorpion stinger and 1 steel',
        'yellow belly syringe': '1 anti-freeze bottle, 1 fertilizer, 1 glass and 2 silver',  
        /* ---- Cooking Station ---- */
        /* Beverage */
        'dirty wastelander': '1 mutfruit, 1 nuka-cola and 2 whiskey',
        'fire belly': '3 aster, 2 black bloodleaf and 1 vodka',
        'purified water': '3 dirty water',
        'vim': '1 acid, 1 corn, 1 mutfruit and 1 purified water',
        'vim captains blend': '1 aster, 1 mirelurk meat and 1 vim',
        'vim quartz': '1 bubblegum, 1 carrot and 1 vim',
        'vim refresh': '1 dandy boy apples, 1 gourd and 1 vim',
        'wares brew': '3 raw sap',
        /* Roast */
        'baked bloatfly': '2 bloatfly meat',
        'bloodbug steak': '1 bloodbug meat',
        'cooked softshell meat': '2 softshell mirelurk meat',
        'crispy squirrel bits': '1 squirrel bits',
        'deathclaw egg omelette': '1 blood pack and 1 deathclaw egg',
        'deathclaw steak': '1 deathclaw meat',
        'fried fog crawler': '1 oil and 1 raw fog crawler meat',
        'grilled radroach': '3 radroach meat',
        'grilled radstag': '1 radstag meat',
        'iguana on a stick': '1 iguana bits and 1 wood',
        'mirelurk cake': '1 mirelurk egg, 1 mirelurk meat, 1 oil and 1 razorgrain',
        'mirelurk egg omelette': '1 dirty water and 1 mmirelurk egg',
        'mirelurk jerky': '1 anti freeze bottle, 2 mirelurk meat and 2 tarberry',
        'mirelurk queen steak': '1 mirelurk queen meat',
        'mole rat chunks': '2 mole rat meat',
        'mutant hound chops': '1 mutant hound meat',
        'mutt chops': '1 mongrel dog meat',
        'poached angler': '1 angler meat',
        'radscorpion egg omelette': '1 purified water and 1 radscorpion egg',
        'radscorpion steak': '1 radscorpion meat',
        'ribeye steak': '1 brahmin meat',
        'roasted mirelurk meat': '2 mirelurk meat',
        'seasoned rabbit skewers': '1 aster, 1 black bloodleaf, 1 blight, 1 lure weed and 1 rabbit leg',
        'slocums buzzbites': '1 coffee tin, 1 dirty water, 1 mirelurk egg, 1 oil and 3 razorgrain',
        'squirrel on a stick': '1 squirrel bits and 1 wood',
        'stingwing filet': '1 stingwing meat',
        'tasty deathclaw omelette': '1 blood pack, 2 carrots, 2 mutfruits, 1 pristine deathclaw egg and 1 purified water',
        'wolf ribs': '1 lure weed and 1 wolf meat',
        'yao guai ribs': '1 yao guai meat',
        'yao guai roast': '1 carrot, 1 tato and 1 yao guai meat',
        /* Utility */
        'vegetable starch': '3 corn, 3 mutfruit, 1 purified water and 3 tato',
        /* Soups */
        'chicken noodle soup': '1 black bloodleaf, 1 carrot, 1 chicken thigh and 1 dirty water',
        'deathclaw wellingham': '1 deathclaw egg, 1 dirty water and 1 tato',
        'gulper slurry': '1 acid, 1 crystal, 3 gulper innards and 1 purified water',
        'iguana soup': '1 carrot, 1 dirty water and 3 iguana btis',
        'noodle soup': '1 dirty water and 1 razorgrain',
        'radstag stew': '1 gourd, 1 radstag meat, 1 silt bean and 1 vodka',
        'squirrel stew': '1 bloodleaf, 1 carrot, 2 dirty water, 1 squirrel bits and 1 tato',
        'vegetable soup': '1 carrot, 1 dirty water and 1 tato',
    },

    RECIPE_EN_US: {
        /* ---- Chemistry Station ---- */
        /* Drugs */
        'berry mentats': 'Berry mentats are made with 1 anti-freeze bottle, 1 mentats and 2 tarberry.',
        'buffjet': 'You will need 1 buffout and 1 jet to make buffjet',
        'buffats': '1 buffout, 1 mentats',
        'fury': '1 berserk syringe, 1 buffout. You will also need the skill Chemist level 1.',
        'grape mentats': '2 hubflower, 1 mentats, 1 whiskey',
        'jet': '2 fertilizer, 1 plastic',
        'jet fuel': '5 flamer fuel, 1 jet. You will also need the skill Chemist level 1.',
        'mentats': '1 abraxo cleaner, 2 brain fungus, 1 lead',
        'orange mentats': '1 asbestos, 3 carrots, 1 mentats',
        'overdrive': '2 acid, 1 nuka-cola, 1 psycho. You will also need the skill Chemist level 1.',
        'psycho': '1 acid, 1 circuitry, 2 hubflower, 1 stimpak',
        'psycho jet': '1 jet, 1 psycho',
        'psychobuff': '1 buffout, 1 psycho',
        'ultrajet': '1 bloodleaf, 1 fertilizer, 1 jet and 2 plastic. You will also need the skill Chemist level 1.',
        /* Grenades */
        'baseball grenade': '2 adhesive, 1 baseball, 2 fertilizer, 1 oil and 2 steel',
        'cryogenic grenade': '3 acid, 3 adhesive, 3 auminium, 2 nuclear material and 1 spring.',
        'fragmentation grenade': '3 adhesive, 2 aluminium, 2 fertilizer, 3 oil and 1 spring',
        'hallucinogen gas grenade': '3 adhesive, 2 aluminium, 1 hallucinogen gas canister and 1 ',
        'Molotov cocktail': '2 adhesive, 1 cloth, 2 glass, 4 oil',
        'Plasma grenade': '4 adhesive, 4 aluminium, 2 circuitry, 3 nuclear material, 1 spring',
        'Pulse grenade': '4 adhesive, 3 aluminium, 1 circuitry, 2 nuclear material, 1 spring',
        /* Healing */
        'glowing blood pack': '1 antiseptic, 1 blood pack, 1 irradiated blood',
        'radaway': '2 antiseptic, 3 glowing fungus, 1 plastic, 1 purified water',
        'refreshing beverage': '3 antiseptic, 1 blood pack, 2 purified water, 2 radaway, 1 stimpak',
        'robot repair kit': '2 circuitry, 4 fusion cell, 2 spring, 1 steel',
        'skeeto spit': '1 blood sac, 1 bloodleaf, 1 glass, 1 steel',
        'stimpak': '2 antiseptic, 1 blood pack, 1 steel',
        /* Mines */
        'bottlecap mine': '2 adhesive, 2 fertilizer, 2 oil, 2 steel, 1 vault-tec lunchbox',
        'cryo mine': '3 acid, 3 adhesive, 4 aluminium, 2 circuitry, 2 nuclear material',
        'fragmentation mine': '3 adhesive, 3 aluminium, 3 fertilizer, 3 oil, 2 steel',
        'plasma mine': '4 adhesive, 5 aluminium, 3 circuitry, 3 fiber optics, 3 nuclear material',
        'pulse mine': '4 adhesive, 4 aluminium, 3 circuitry, 2 fiber optics, 3 nuclear material',
        /* Utility */
        'cutting fluid': '2 acid, 8 bone, 2 purified water and 3 steel',
        'modified bowling ball': '1 acid, 1 bowling ball, 1 oil',
        /* Syringer ammo */
        'berserk syringe': '1 anti freeze bottle, 1 bourbon, 1 dirty water and 1 steel',
        'bleed out syringe': '1 fiberglass, 1 oil and 1 steel',
        'bloatfly larva': '1 bloatfly gland, 1 glass and 1 psycho',
        'endangerol syringe': '1 acid, 1 glass, 1 med-x and 1 pencil',
        'lock joint syringe': '1 dirty water, 4 lead, 1 steel, 1 stingwing barb and 2 tarberry',
        'mind cloud syringe': '1 abraxo cleaner, 2 asbestos, 1 glass and 1 purified water',
        'pax syringe': '2 mutfruit, 1 nuka-cola and 1 steel',
        'radscorpion venom syringe': '1 glass, 1 radscorpion stinger and 1 steel',
        'yellow belly syringe': '1 anti-freeze bottle, 1 fertilizer, 1 glass and 2 silver',   
    },
    RECIPE_DE_DE: {
        /* ---- Chemistry Station ---- */
        /* Drugs */
        'berry mentats': 'Berry mentats are made with 1 anti-freeze bottle, 1 mentats and 2 tarberry.',
        'buffjet': 'You will need 1 buffout and 1 jet to make buffjet',
        'buffats': '1 buffout, 1 mentats',
        'fury': '1 berserk syringe, 1 buffout. You will also need the skill Chemist level 1.',
        'grape mentats': '2 hubflower, 1 mentats, 1 whiskey',
        'jet': '2 fertilizer, 1 plastic',
        'jet fuel': '5 flamer fuel, 1 jet. You will also need the skill Chemist level 1.',
        'mentats': '1 abraxo cleaner, 2 brain fungus, 1 lead',
        'orange mentats': '1 asbestos, 3 carrots, 1 mentats',
        'overdrive': '2 acid, 1 nuka-cola, 1 psycho. You will also need the skill Chemist level 1.',
        'psycho': '1 acid, 1 circuitry, 2 hubflower, 1 stimpak',
        'psycho jet': '1 jet, 1 psycho',
        'psychobuff': '1 buffout, 1 psycho',
        'ultrajet': '1 bloodleaf, 1 fertilizer, 1 jet and 2 plastic. You will also need the skill Chemist level 1.',
        /* Grenades */
        'baseball grenade': '2 adhesive, 1 baseball, 2 fertilizer, 1 oil and 2 steel',
        'cryogenic grenade': '3 acid, 3 adhesive, 3 auminium, 2 nuclear material and 1 spring.',
        'fragmentation grenade': '3 adhesive, 2 aluminium, 2 fertilizer, 3 oil and 1 spring',
        'hallucinogen gas grenade': '3 adhesive, 2 aluminium, 1 hallucinogen gas canister and 1 ',
        'Molotov cocktail': '2 adhesive, 1 cloth, 2 glass, 4 oil',
        'Plasma grenade': '4 adhesive, 4 aluminium, 2 circuitry, 3 nuclear material, 1 spring',
        'Pulse grenade': '4 adhesive, 3 aluminium, 1 circuitry, 2 nuclear material, 1 spring',
        /* Healing */
        'glowing blood pack': '1 antiseptic, 1 blood pack, 1 irradiated blood',
        'radaway': '2 antiseptic, 3 glowing fungus, 1 plastic, 1 purified water',
        'refreshing beverage': '3 antiseptic, 1 blood pack, 2 purified water, 2 radaway, 1 stimpak',
        'robot repair kit': '2 circuitry, 4 fusion cell, 2 spring, 1 steel',
        'skeeto spit': '1 blood sac, 1 bloodleaf, 1 glass, 1 steel',
        'stimpak': '2 antiseptic, 1 blood pack, 1 steel',
        /* Mines */
        'bottlecap mine': '2 adhesive, 2 fertilizer, 2 oil, 2 steel, 1 vault-tec lunchbox',
        'cryo mine': '3 acid, 3 adhesive, 4 aluminium, 2 circuitry, 2 nuclear material',
        'fragmentation mine': '3 adhesive, 3 aluminium, 3 fertilizer, 3 oil, 2 steel',
        'plasma mine': '4 adhesive, 5 aluminium, 3 circuitry, 3 fiber optics, 3 nuclear material',
        'pulse mine': '4 adhesive, 4 aluminium, 3 circuitry, 2 fiber optics, 3 nuclear material',
        /* Utility */
        'cutting fluid': '2 acid, 8 bone, 2 purified water and 3 steel',
        'modified bowling ball': '1 acid, 1 bowling ball, 1 oil',
        /* Syringer ammo */
        'berserk syringe': '1 anti freeze bottle, 1 bourbon, 1 dirty water and 1 steel',
        'bleed out syringe': '1 fiberglass, 1 oil and 1 steel',
        'bloatfly larva': '1 bloatfly gland, 1 glass and 1 psycho',
        'endangerol syringe': '1 acid, 1 glass, 1 med-x and 1 pencil',
        'lock joint syringe': '1 dirty water, 4 lead, 1 steel, 1 stingwing barb and 2 tarberry',
        'mind cloud syringe': '1 abraxo cleaner, 2 asbestos, 1 glass and 1 purified water',
        'pax syringe': '2 mutfruit, 1 nuka-cola and 1 steel',
        'radscorpion venom syringe': '1 glass, 1 radscorpion stinger and 1 steel',
        'yellow belly syringe': '1 anti-freeze bottle, 1 fertilizer, 1 glass and 2 silver',   
    },
};
