/* eslint-disable  func-names */
/* eslint quote-props: ["error", "consistent"]*/

/* THIS IS A WORK IN PROGRESS */

module.exports = {
    RECIPE_EN_GB: {
        /* ---- Chemistry Station ---- */
        /* Drugs */
        'berry mentats': 'berry mentats are made with 1 anti-freeze bottle, 1 mentats and 2 tarberry.',
        'buffjet': 'for buffjet you will need 1 buffout and 1 jet to make buffjet',
        'buffats': 'buffats require 1 buffout and 1 mentats to make',
        'fury': 'for fury you will need 1 berserk syringe and 1 buffout',
        'grape mentats': 'grape mentats are made with 2 hubflowers, 1 mentats and 1 whiskey',
        'jet': 'jet is made with 2 fertilizer, 1 plastic',
        'jet fuel': 'for jet fuel you will need 5 flamer fuel, 1 jet',
        'mentats': 'mentats require 1 abraxo cleaner, 2 brain fungus, 1 lead',
        'orange mentats': 'to create orange mentats you will need 1 asbestos, 3 carrots, 1 mentats',
        'overdrive': 'overdrive can be made with 2 acid, 1 nuka-cola, 1 psycho',
        'psycho': 'psycho is made with 1 acid, 1 circuitry, 2 hubflower, 1 stimpak',
        'psycho jet': 'for psycho jet you will need 1 jet, 1 psycho',
        'psychobuff': 'psychobuff requires 1 buffout, 1 psycho',
        'ultrajet': 'for ultrajet you will need 1 bloodleaf, 1 fertilizer, 1 jet and 2 plastic',
        /* Grenades */
        'baseball grenade': 'a baseball grenade can be made with 2 adhesive, 1 baseball, 2 fertilizer, 1 oil and 2 steel',
        'cryogenic grenade': 'cryogenic grenades are made with cryogenic grenade is made with 3 acid, 3 adhesive, 3 auminium, 2 nuclear material and 1 spring.',
        'fragmentation grenade': 'for a fragmentation grenade you will need 3 adhesive, 2 aluminium, 2 fertilizer, 3 oil and 1 spring',
        'hallucinogen gas grenade': 'hallucinogen gas uses 3 adhesive, 2 aluminium, 1 hallucinogen gas canister and 1 ',
        'Molotov cocktail': 'for a molotov cocktail you will need 2 adhesive, 1 cloth, 2 glass, 4 oil',
        'Plasma grenade': 'a plasma grenade can be made with 4 adhesive, 4 aluminium, 2 circuitry, 3 nuclear material, 1 spring',
        'Pulse grenade': 'pulse grenades are made with 4 adhesive, 3 aluminium, 1 circuitry, 2 nuclear material, 1 spring',
        /* Healing */
        'glowing blood pack': 'for a glowing blood pack you will need 1 antiseptic, 1 blood pack, 1 irradiated blood',
        'radaway': 'radaway requires 2 antiseptic, 3 glowing fungus, 1 plastic, 1 purified water',
        'refreshing beverage': 'for a refreshing beverage you will need 3 antiseptic, 1 blood pack, 2 purified water, 2 radaway, 1 stimpak',
        'robot repair kit': 'a robot repair kit can be made with 2 circuitry, 4 fusion cell, 2 springand  1 steel',
        'skeeto spit': 'skeeto spit is made with 1 blood sac, 1 bloodleaf, 1 glass and 1 steel',
        'stimpak': 'for a stimpak you will need 2 antiseptic, 1 blood pack and 1 steel',
        /* Mines */
        'bottlecap mine': 'a bottlecap mine requires 2 adhesive, 2 fertilizer, 2 oil, 2 steel and 1 vault-tec lunchbox',
        'cryo mine': 'to build a cryo mine you will need 3 acid, 3 adhesive, 4 aluminium, 2 circuitry and 2 nuclear material',
        'fragmentation mine': 'a fragmentation mine can be made with 3 adhesive, 3 aluminium, 3 fertilizer, 3 oil and 2 steel',
        'plasma mine': 'plasma mines are made with 4 adhesive, 5 aluminium, 3 circuitry, 3 fiber optics and 3 nuclear material',
        'pulse mine': 'for a pulse mine you will need 4 adhesive, 4 aluminium, 3 circuitry, 2 fiber optics and 3 nuclear material',
        /* Utility */
        'cutting fluid': 'cutting fluid requires 2 acid, 8 bone, 2 purified water and 3 steel',
        'modified bowling ball': 'to make a modified bowling ball you will need 1 acid, 1 bowling ball and 1 oil',
        /* Syringer ammo */
        'berserk syringe': 'a berserk syringe can be made with 1 anti freeze bottle, 1 bourbon, 1 dirty water and 1 steel',
        'bleed out syringe': 'bleed out syringe is made with 1 fiberglass, 1 oil and 1 steel',
        'bloatfly larva': 'for a bloatfly larva you will need 1 bloatfly gland, 1 glass and 1 psycho',
        'endangerol syringe': 'an endangerol syringe uses 1 acid, 1 glass, 1 med-x and 1 pencil',
        'lock joint syringe': 'to create a lock joint syringe you will need 1 dirty water, 4 lead, 1 steel, 1 stingwing barb and 2 tarberry',
        'mind cloud syringe': 'a mind cloud syringe can be made with 1 abraxo cleaner, 2 asbestos, 1 glass and 1 purified water',
        'pax syringe': 'pax syringe is made with 2 mutfruit, 1 nuka-cola and 1 steel',
        'radscorpion venom syringe': 'for a radscorpion venom syringe you will need 1 glass, 1 radscorpion stinger and 1 steel',
        'yellow belly syringe': 'a yellow belly syringe requires 1 anti-freeze bottle, 1 fertilizer, 1 glass and 2 silver',  
        /* ---- Cooking Station ---- */
        /* Beverage */
        'dirty wastelander': 'for a dirty wastelander you will need 1 mutfruit, 1 nuka-cola and 2 whiskey',
        'fire belly': 'a fire belly can be made with 3 aster, 2 black bloodleaf and 1 vodka',
        'purified water': 'purified water is made with 3 dirty water',
        'vim': 'for vim you will need 1 acid, 1 corn, 1 mutfruit and 1 purified water',
        'vim captains blend': 'a vim captains blend uses 1 aster, 1 mirelurk meat and 1 vim',
        'vim quartz': 'to make a vim quartz you will need 1 bubblegum, 1 carrot and 1 vim',
        'vim refresh': 'a vim refresh can be made with 1 dandy boy apples, 1 gourd and 1 vim',
        'wares brew': 'wares brew is made with 3 raw sap',
        /* Roast */
        'baked bloatfly': 'for a baked bloatfly you will need 2 bloatfly meat',
        'bloodbug steak': 'a bloodbug steak requires just 1 bloodbug meat',
        'cooked softshell meat': 'to make cooked softshell meat you will need 2 softshell mirelurk meat',
        'crispy squirrel bits': 'for crispy squirrel bits you just need 1 squirrel bits',
        'deathclaw egg omelette': 'deathclaw omelette is made with 1 blood pack and 1 deathclaw egg',
        'deathclaw steak': 'for a deathclaw steak you will need 1 deathclaw meat',
        'fried fog crawler': 'a fried fog crawler requires 1 oil and 1 raw fog crawler meat',
        'grilled radroach': 'to make a grilled radroach you will need 3 radroach meat',
        'grilled radstag': 'for a grilled radstag you just need 1 radstag meat',
        'iguana on a stick': 'iguana on a stick is made with 1 iguana bits and 1 wood',
        'mirelurk cake': 'for a mirelurk cake you will need 1 mirelurk egg, 1 mirelurk meat, 1 oil and 1 razorgrain',
        'mirelurk egg omelette': 'a mirelurk egg omelette uses 1 dirty water and 1 mmirelurk egg',
        'mirelurk jerky': 'for mirelurk jelly you will need 1 anti freeze bottle, 2 mirelurk meat and 2 tarberry',
        'mirelurk queen steak': 'a mirelurk queen steak can be made with 1 mirelurk queen meat',
        'mole rat chunks': 'mole rat chnks are made with 2 mole rat meat',
        'mutant hound chops': 'for the mutant hound chops you will need 1 mutant hound meat',
        'mutt chops': 'the mutt chops require 1 mongrel dog meat',
        'poached angler': 'for a poached angler you will need 1 angler meat',
        'radscorpion egg omelette': 'a radscorpion egg omelette can be made with 1 purified water and 1 radscorpion egg',
        'radscorpion steak': 'radscorpion steak is made with 1 radscorpion meat',
        'ribeye steak': 'for a ribeye steak you will need 1 brahmin meat',
        'roasted mirelurk meat': 'some roasted mirelurk steak requires 2 mirelurk meat',
        'seasoned rabbit skewers': 'for seasoned rabbit skewers you will need 1 aster, 1 black bloodleaf, 1 blight, 1 lure weed and 1 rabbit leg',
        'slocums buzzbites': 'the slocums buzzbites can be made with 1 coffee tin, 1 dirty water, 1 mirelurk egg, 1 oil and 3 razorgrain',
        'squirrel on a stick': 'squirrel on a stick is made with 1 squirrel bits and 1 wood',
        'stingwing filet': 'for a stingwing filet you will need 1 stingwing meat',
        'tasty deathclaw omelette': 'a tasty deathclaw omelette uses 1 blood pack, 2 carrots, 2 mutfruits, 1 pristine deathclaw egg and 1 purified water',
        'wolf ribs': 'to cook wolf ribs you will need 1 lure weed and 1 wolf meat',
        'yao guai ribs': 'the yao guai ribs can be made with just 1 yao guai meat',
        'yao guai roast': 'yao guai roast is made with 1 carrot, 1 tato and 1 yao guai meat',
        /* Utility */
        'vegetable starch': 'for vegetable starch you will need 3 corn, 3 mutfruit, 1 purified water and 3 tato',
        /* Soups */
        'chicken noodle soup': 'a chicken noodle soup requires 1 black bloodleaf, 1 carrot, 1 chicken thigh and 1 dirty water',
        'deathclaw wellingham': 'to make deathclaw wellingham you will need 1 deathclaw egg, 1 dirty water and 1 tato',
        'gulper slurry': 'a gulper slurry can be made with 1 acid, 1 crystal, 3 gulper innards and 1 purified water',
        'iguana soup': 'iguana soup is made with 1 carrot, 1 dirty water and 3 iguana btis',
        'noodle soup': 'for a noodle soup you will need 1 dirty water and 1 razorgrain',
        'radstag stew': 'a radstad stew requires 1 gourd, 1 radstag meat, 1 silt bean and 1 vodka',
        'squirrel stew': 'to cook squirrel stew you will need 1 bloodleaf, 1 carrot, 2 dirty water, 1 squirrel bits and 1 tato',
        'vegetable soup': 'vegetable soup uses 1 carrot, 1 dirty water and 1 tato',
    },

    RECIPE_EN_US: {
         /* ---- Chemistry Station ---- */
        /* Drugs */
        'berry mentats': 'berry mentats are made with 1 anti-freeze bottle, 1 mentats and 2 tarberry.',
        'buffjet': 'for buffjet you will need 1 buffout and 1 jet to make buffjet',
        'buffats': 'buffats require 1 buffout and 1 mentats to make',
        'fury': 'for fury you will need 1 berserk syringe and 1 buffout',
        'grape mentats': 'grape mentats are made with 2 hubflowers, 1 mentats and 1 whiskey',
        'jet': 'jet is made with 2 fertilizer, 1 plastic',
        'jet fuel': 'for jet fuel you will need 5 flamer fuel, 1 jet',
        'mentats': 'mentats require 1 abraxo cleaner, 2 brain fungus, 1 lead',
        'orange mentats': 'to create orange mentats you will need 1 asbestos, 3 carrots, 1 mentats',
        'overdrive': 'overdrive can be made with 2 acid, 1 nuka-cola, 1 psycho',
        'psycho': 'psycho is made with 1 acid, 1 circuitry, 2 hubflower, 1 stimpak',
        'psycho jet': 'for psycho jet you will need 1 jet, 1 psycho',
        'psychobuff': 'psychobuff requires 1 buffout, 1 psycho',
        'ultrajet': 'for ultrajet you will need 1 bloodleaf, 1 fertilizer, 1 jet and 2 plastic',
        /* Grenades */
        'baseball grenade': 'a baseball grenade can be made with 2 adhesive, 1 baseball, 2 fertilizer, 1 oil and 2 steel',
        'cryogenic grenade': 'cryogenic grenades are made with cryogenic grenade is made with 3 acid, 3 adhesive, 3 auminium, 2 nuclear material and 1 spring.',
        'fragmentation grenade': 'for a fragmentation grenade you will need 3 adhesive, 2 aluminium, 2 fertilizer, 3 oil and 1 spring',
        'hallucinogen gas grenade': 'hallucinogen gas uses 3 adhesive, 2 aluminium, 1 hallucinogen gas canister and 1 ',
        'Molotov cocktail': 'for a molotov cocktail you will need 2 adhesive, 1 cloth, 2 glass, 4 oil',
        'Plasma grenade': 'a plasma grenade can be made with 4 adhesive, 4 aluminium, 2 circuitry, 3 nuclear material, 1 spring',
        'Pulse grenade': 'pulse grenades are made with 4 adhesive, 3 aluminium, 1 circuitry, 2 nuclear material, 1 spring',
        /* Healing */
        'glowing blood pack': 'for a glowing blood pack you will need 1 antiseptic, 1 blood pack, 1 irradiated blood',
        'radaway': 'radaway requires 2 antiseptic, 3 glowing fungus, 1 plastic, 1 purified water',
        'refreshing beverage': 'for a refreshing beverage you will need 3 antiseptic, 1 blood pack, 2 purified water, 2 radaway, 1 stimpak',
        'robot repair kit': 'a robot repair kit can be made with 2 circuitry, 4 fusion cell, 2 springand  1 steel',
        'skeeto spit': 'skeeto spit is made with 1 blood sac, 1 bloodleaf, 1 glass and 1 steel',
        'stimpak': 'for a stimpak you will need 2 antiseptic, 1 blood pack and 1 steel',
        /* Mines */
        'bottlecap mine': 'a bottlecap mine requires 2 adhesive, 2 fertilizer, 2 oil, 2 steel and 1 vault-tec lunchbox',
        'cryo mine': 'to build a cryo mine you will need 3 acid, 3 adhesive, 4 aluminium, 2 circuitry and 2 nuclear material',
        'fragmentation mine': 'a fragmentation mine can be made with 3 adhesive, 3 aluminium, 3 fertilizer, 3 oil and 2 steel',
        'plasma mine': 'plasma mines are made with 4 adhesive, 5 aluminium, 3 circuitry, 3 fiber optics and 3 nuclear material',
        'pulse mine': 'for a pulse mine you will need 4 adhesive, 4 aluminium, 3 circuitry, 2 fiber optics and 3 nuclear material',
        /* Utility */
        'cutting fluid': 'cutting fluid requires 2 acid, 8 bone, 2 purified water and 3 steel',
        'modified bowling ball': 'to make a modified bowling ball you will need 1 acid, 1 bowling ball and 1 oil',
        /* Syringer ammo */
        'berserk syringe': 'a berserk syringe can be made with 1 anti freeze bottle, 1 bourbon, 1 dirty water and 1 steel',
        'bleed out syringe': 'bleed out syringe is made with 1 fiberglass, 1 oil and 1 steel',
        'bloatfly larva': 'for a bloatfly larva you will need 1 bloatfly gland, 1 glass and 1 psycho',
        'endangerol syringe': 'an endangerol syringe uses 1 acid, 1 glass, 1 med-x and 1 pencil',
        'lock joint syringe': 'to create a lock joint syringe you will need 1 dirty water, 4 lead, 1 steel, 1 stingwing barb and 2 tarberry',
        'mind cloud syringe': 'a mind cloud syringe can be made with 1 abraxo cleaner, 2 asbestos, 1 glass and 1 purified water',
        'pax syringe': 'pax syringe is made with 2 mutfruit, 1 nuka-cola and 1 steel',
        'radscorpion venom syringe': 'for a radscorpion venom syringe you will need 1 glass, 1 radscorpion stinger and 1 steel',
        'yellow belly syringe': 'a yellow belly syringe requires 1 anti-freeze bottle, 1 fertilizer, 1 glass and 2 silver',  
        /* ---- Cooking Station ---- */
        /* Beverage */
        'dirty wastelander': 'for a dirty wastelander you will need 1 mutfruit, 1 nuka-cola and 2 whiskey',
        'fire belly': 'a fire belly can be made with 3 aster, 2 black bloodleaf and 1 vodka',
        'purified water': 'purified water is made with 3 dirty water',
        'vim': 'for vim you will need 1 acid, 1 corn, 1 mutfruit and 1 purified water',
        'vim captains blend': 'a vim captains blend uses 1 aster, 1 mirelurk meat and 1 vim',
        'vim quartz': 'to make a vim quartz you will need 1 bubblegum, 1 carrot and 1 vim',
        'vim refresh': 'a vim refresh can be made with 1 dandy boy apples, 1 gourd and 1 vim',
        'wares brew': 'wares brew is made with 3 raw sap',
        /* Roast */
        'baked bloatfly': 'for a baked bloatfly you will need 2 bloatfly meat',
        'bloodbug steak': 'a bloodbug steak requires just 1 bloodbug meat',
        'cooked softshell meat': 'to make cooked softshell meat you will need 2 softshell mirelurk meat',
        'crispy squirrel bits': 'for crispy squirrel bits you just need 1 squirrel bits',
        'deathclaw egg omelette': 'deathclaw omelette is made with 1 blood pack and 1 deathclaw egg',
        'deathclaw steak': 'for a deathclaw steak you will need 1 deathclaw meat',
        'fried fog crawler': 'a fried fog crawler requires 1 oil and 1 raw fog crawler meat',
        'grilled radroach': 'to make a grilled radroach you will need 3 radroach meat',
        'grilled radstag': 'for a grilled radstag you just need 1 radstag meat',
        'iguana on a stick': 'iguana on a stick is made with 1 iguana bits and 1 wood',
        'mirelurk cake': 'for a mirelurk cake you will need 1 mirelurk egg, 1 mirelurk meat, 1 oil and 1 razorgrain',
        'mirelurk egg omelette': 'a mirelurk egg omelette uses 1 dirty water and 1 mmirelurk egg',
        'mirelurk jerky': 'for mirelurk jelly you will need 1 anti freeze bottle, 2 mirelurk meat and 2 tarberry',
        'mirelurk queen steak': 'a mirelurk queen steak can be made with 1 mirelurk queen meat',
        'mole rat chunks': 'mole rat chnks are made with 2 mole rat meat',
        'mutant hound chops': 'for the mutant hound chops you will need 1 mutant hound meat',
        'mutt chops': 'the mutt chops require 1 mongrel dog meat',
        'poached angler': 'for a poached angler you will need 1 angler meat',
        'radscorpion egg omelette': 'a radscorpion egg omelette can be made with 1 purified water and 1 radscorpion egg',
        'radscorpion steak': 'radscorpion steak is made with 1 radscorpion meat',
        'ribeye steak': 'for a ribeye steak you will need 1 brahmin meat',
        'roasted mirelurk meat': 'some roasted mirelurk steak requires 2 mirelurk meat',
        'seasoned rabbit skewers': 'for seasoned rabbit skewers you will need 1 aster, 1 black bloodleaf, 1 blight, 1 lure weed and 1 rabbit leg',
        'slocums buzzbites': 'the slocums buzzbites can be made with 1 coffee tin, 1 dirty water, 1 mirelurk egg, 1 oil and 3 razorgrain',
        'squirrel on a stick': 'squirrel on a stick is made with 1 squirrel bits and 1 wood',
        'stingwing filet': 'for a stingwing filet you will need 1 stingwing meat',
        'tasty deathclaw omelette': 'a tasty deathclaw omelette uses 1 blood pack, 2 carrots, 2 mutfruits, 1 pristine deathclaw egg and 1 purified water',
        'wolf ribs': 'to cook wolf ribs you will need 1 lure weed and 1 wolf meat',
        'yao guai ribs': 'the yao guai ribs can be made with just 1 yao guai meat',
        'yao guai roast': 'yao guai roast is made with 1 carrot, 1 tato and 1 yao guai meat',
        /* Utility */
        'vegetable starch': 'for vegetable starch you will need 3 corn, 3 mutfruit, 1 purified water and 3 tato',
        /* Soups */
        'chicken noodle soup': 'a chicken noodle soup requires 1 black bloodleaf, 1 carrot, 1 chicken thigh and 1 dirty water',
        'deathclaw wellingham': 'to make deathclaw wellingham you will need 1 deathclaw egg, 1 dirty water and 1 tato',
        'gulper slurry': 'a gulper slurry can be made with 1 acid, 1 crystal, 3 gulper innards and 1 purified water',
        'iguana soup': 'iguana soup is made with 1 carrot, 1 dirty water and 3 iguana btis',
        'noodle soup': 'for a noodle soup you will need 1 dirty water and 1 razorgrain',
        'radstag stew': 'a radstad stew requires 1 gourd, 1 radstag meat, 1 silt bean and 1 vodka',
        'squirrel stew': 'to cook squirrel stew you will need 1 bloodleaf, 1 carrot, 2 dirty water, 1 squirrel bits and 1 tato',
        'vegetable soup': 'vegetable soup uses 1 carrot, 1 dirty water and 1 tato',
    },
    RECIPE_DE_DE: {
        /* ---- Chemistry Station ---- */
        /* Drugs */
        'berry mentats': 'berry mentats are made with 1 anti-freeze bottle, 1 mentats and 2 tarberry.',
        'buffjet': 'for buffjet you will need 1 buffout and 1 jet to make buffjet',
        'buffats': 'buffats require 1 buffout and 1 mentats to make',
        'fury': 'for fury you will need 1 berserk syringe and 1 buffout',
        'grape mentats': 'grape mentats are made with 2 hubflowers, 1 mentats and 1 whiskey',
        'jet': 'jet is made with 2 fertilizer, 1 plastic',
        'jet fuel': 'for jet fuel you will need 5 flamer fuel, 1 jet',
        'mentats': 'mentats require 1 abraxo cleaner, 2 brain fungus, 1 lead',
        'orange mentats': 'to create orange mentats you will need 1 asbestos, 3 carrots, 1 mentats',
        'overdrive': 'overdrive can be made with 2 acid, 1 nuka-cola, 1 psycho',
        'psycho': 'psycho is made with 1 acid, 1 circuitry, 2 hubflower, 1 stimpak',
        'psycho jet': 'for psycho jet you will need 1 jet, 1 psycho',
        'psychobuff': 'psychobuff requires 1 buffout, 1 psycho',
        'ultrajet': 'for ultrajet you will need 1 bloodleaf, 1 fertilizer, 1 jet and 2 plastic',
        /* Grenades */
        'baseball grenade': 'a baseball grenade can be made with 2 adhesive, 1 baseball, 2 fertilizer, 1 oil and 2 steel',
        'cryogenic grenade': 'cryogenic grenades are made with cryogenic grenade is made with 3 acid, 3 adhesive, 3 auminium, 2 nuclear material and 1 spring.',
        'fragmentation grenade': 'for a fragmentation grenade you will need 3 adhesive, 2 aluminium, 2 fertilizer, 3 oil and 1 spring',
        'hallucinogen gas grenade': 'hallucinogen gas uses 3 adhesive, 2 aluminium, 1 hallucinogen gas canister and 1 ',
        'Molotov cocktail': 'for a molotov cocktail you will need 2 adhesive, 1 cloth, 2 glass, 4 oil',
        'Plasma grenade': 'a plasma grenade can be made with 4 adhesive, 4 aluminium, 2 circuitry, 3 nuclear material, 1 spring',
        'Pulse grenade': 'pulse grenades are made with 4 adhesive, 3 aluminium, 1 circuitry, 2 nuclear material, 1 spring',
        /* Healing */
        'glowing blood pack': 'for a glowing blood pack you will need 1 antiseptic, 1 blood pack, 1 irradiated blood',
        'radaway': 'radaway requires 2 antiseptic, 3 glowing fungus, 1 plastic, 1 purified water',
        'refreshing beverage': 'for a refreshing beverage you will need 3 antiseptic, 1 blood pack, 2 purified water, 2 radaway, 1 stimpak',
        'robot repair kit': 'a robot repair kit can be made with 2 circuitry, 4 fusion cell, 2 springand  1 steel',
        'skeeto spit': 'skeeto spit is made with 1 blood sac, 1 bloodleaf, 1 glass and 1 steel',
        'stimpak': 'for a stimpak you will need 2 antiseptic, 1 blood pack and 1 steel',
        /* Mines */
        'bottlecap mine': 'a bottlecap mine requires 2 adhesive, 2 fertilizer, 2 oil, 2 steel and 1 vault-tec lunchbox',
        'cryo mine': 'to build a cryo mine you will need 3 acid, 3 adhesive, 4 aluminium, 2 circuitry and 2 nuclear material',
        'fragmentation mine': 'a fragmentation mine can be made with 3 adhesive, 3 aluminium, 3 fertilizer, 3 oil and 2 steel',
        'plasma mine': 'plasma mines are made with 4 adhesive, 5 aluminium, 3 circuitry, 3 fiber optics and 3 nuclear material',
        'pulse mine': 'for a pulse mine you will need 4 adhesive, 4 aluminium, 3 circuitry, 2 fiber optics and 3 nuclear material',
        /* Utility */
        'cutting fluid': 'cutting fluid requires 2 acid, 8 bone, 2 purified water and 3 steel',
        'modified bowling ball': 'to make a modified bowling ball you will need 1 acid, 1 bowling ball and 1 oil',
        /* Syringer ammo */
        'berserk syringe': 'a berserk syringe can be made with 1 anti freeze bottle, 1 bourbon, 1 dirty water and 1 steel',
        'bleed out syringe': 'bleed out syringe is made with 1 fiberglass, 1 oil and 1 steel',
        'bloatfly larva': 'for a bloatfly larva you will need 1 bloatfly gland, 1 glass and 1 psycho',
        'endangerol syringe': 'an endangerol syringe uses 1 acid, 1 glass, 1 med-x and 1 pencil',
        'lock joint syringe': 'to create a lock joint syringe you will need 1 dirty water, 4 lead, 1 steel, 1 stingwing barb and 2 tarberry',
        'mind cloud syringe': 'a mind cloud syringe can be made with 1 abraxo cleaner, 2 asbestos, 1 glass and 1 purified water',
        'pax syringe': 'pax syringe is made with 2 mutfruit, 1 nuka-cola and 1 steel',
        'radscorpion venom syringe': 'for a radscorpion venom syringe you will need 1 glass, 1 radscorpion stinger and 1 steel',
        'yellow belly syringe': 'a yellow belly syringe requires 1 anti-freeze bottle, 1 fertilizer, 1 glass and 2 silver',  
        /* ---- Cooking Station ---- */
        /* Beverage */
        'dirty wastelander': 'for a dirty wastelander you will need 1 mutfruit, 1 nuka-cola and 2 whiskey',
        'fire belly': 'a fire belly can be made with 3 aster, 2 black bloodleaf and 1 vodka',
        'purified water': 'purified water is made with 3 dirty water',
        'vim': 'for vim you will need 1 acid, 1 corn, 1 mutfruit and 1 purified water',
        'vim captains blend': 'a vim captains blend uses 1 aster, 1 mirelurk meat and 1 vim',
        'vim quartz': 'to make a vim quartz you will need 1 bubblegum, 1 carrot and 1 vim',
        'vim refresh': 'a vim refresh can be made with 1 dandy boy apples, 1 gourd and 1 vim',
        'wares brew': 'wares brew is made with 3 raw sap',
        /* Roast */
        'baked bloatfly': 'for a baked bloatfly you will need 2 bloatfly meat',
        'bloodbug steak': 'a bloodbug steak requires just 1 bloodbug meat',
        'cooked softshell meat': 'to make cooked softshell meat you will need 2 softshell mirelurk meat',
        'crispy squirrel bits': 'for crispy squirrel bits you just need 1 squirrel bits',
        'deathclaw egg omelette': 'deathclaw omelette is made with 1 blood pack and 1 deathclaw egg',
        'deathclaw steak': 'for a deathclaw steak you will need 1 deathclaw meat',
        'fried fog crawler': 'a fried fog crawler requires 1 oil and 1 raw fog crawler meat',
        'grilled radroach': 'to make a grilled radroach you will need 3 radroach meat',
        'grilled radstag': 'for a grilled radstag you just need 1 radstag meat',
        'iguana on a stick': 'iguana on a stick is made with 1 iguana bits and 1 wood',
        'mirelurk cake': 'for a mirelurk cake you will need 1 mirelurk egg, 1 mirelurk meat, 1 oil and 1 razorgrain',
        'mirelurk egg omelette': 'a mirelurk egg omelette uses 1 dirty water and 1 mmirelurk egg',
        'mirelurk jerky': 'for mirelurk jelly you will need 1 anti freeze bottle, 2 mirelurk meat and 2 tarberry',
        'mirelurk queen steak': 'a mirelurk queen steak can be made with 1 mirelurk queen meat',
        'mole rat chunks': 'mole rat chnks are made with 2 mole rat meat',
        'mutant hound chops': 'for the mutant hound chops you will need 1 mutant hound meat',
        'mutt chops': 'the mutt chops require 1 mongrel dog meat',
        'poached angler': 'for a poached angler you will need 1 angler meat',
        'radscorpion egg omelette': 'a radscorpion egg omelette can be made with 1 purified water and 1 radscorpion egg',
        'radscorpion steak': 'radscorpion steak is made with 1 radscorpion meat',
        'ribeye steak': 'for a ribeye steak you will need 1 brahmin meat',
        'roasted mirelurk meat': 'some roasted mirelurk steak requires 2 mirelurk meat',
        'seasoned rabbit skewers': 'for seasoned rabbit skewers you will need 1 aster, 1 black bloodleaf, 1 blight, 1 lure weed and 1 rabbit leg',
        'slocums buzzbites': 'the slocums buzzbites can be made with 1 coffee tin, 1 dirty water, 1 mirelurk egg, 1 oil and 3 razorgrain',
        'squirrel on a stick': 'squirrel on a stick is made with 1 squirrel bits and 1 wood',
        'stingwing filet': 'for a stingwing filet you will need 1 stingwing meat',
        'tasty deathclaw omelette': 'a tasty deathclaw omelette uses 1 blood pack, 2 carrots, 2 mutfruits, 1 pristine deathclaw egg and 1 purified water',
        'wolf ribs': 'to cook wolf ribs you will need 1 lure weed and 1 wolf meat',
        'yao guai ribs': 'the yao guai ribs can be made with just 1 yao guai meat',
        'yao guai roast': 'yao guai roast is made with 1 carrot, 1 tato and 1 yao guai meat',
        /* Utility */
        'vegetable starch': 'for vegetable starch you will need 3 corn, 3 mutfruit, 1 purified water and 3 tato',
        /* Soups */
        'chicken noodle soup': 'a chicken noodle soup requires 1 black bloodleaf, 1 carrot, 1 chicken thigh and 1 dirty water',
        'deathclaw wellingham': 'to make deathclaw wellingham you will need 1 deathclaw egg, 1 dirty water and 1 tato',
        'gulper slurry': 'a gulper slurry can be made with 1 acid, 1 crystal, 3 gulper innards and 1 purified water',
        'iguana soup': 'iguana soup is made with 1 carrot, 1 dirty water and 3 iguana btis',
        'noodle soup': 'for a noodle soup you will need 1 dirty water and 1 razorgrain',
        'radstag stew': 'a radstad stew requires 1 gourd, 1 radstag meat, 1 silt bean and 1 vodka',
        'squirrel stew': 'to cook squirrel stew you will need 1 bloodleaf, 1 carrot, 2 dirty water, 1 squirrel bits and 1 tato',
        'vegetable soup': 'vegetable soup uses 1 carrot, 1 dirty water and 1 tato',
    },
};
